GET http://localhost:8080/api/users/profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTQyNTU0NTYsImlhdCI6MTc1Mzk5NjI1Niwic3ViIjoiZGZjY2M1YjMtOWQ2Mi00NTBhLWJiOTAtMzJjY2NkOGQ1ZGNhIiwidXNlcmRhdGEiOnsiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIiwibmFtZSI6IkpvaG4gRG9lIiwicm9sZUlkIjoyLCJyb2xlTmFtZSI6InVzZXIiLCJ1c2VybmFtZSI6ImpvaG5kb2UifX0.IPlxnOOa9WzaVaHWF-cnTKgBGv56arvjzLpKHA7vuIsGPyhl8ERcJwbjgeSwbJMneeky6VvWeTqOsJ_6yC_OOaIiU4GH1gYrz50hLh7AuD-t3ZtTaxsmMjSxNdA51iw_qXbK29_VPgJZ4wUWUdieLKtILqJaeaRF8Ahacw1rX05vVVkVK7cAc1sJUspekXAUdZwko5XzpiwsPplXYb03VMEB-SiBv3oudFQQvmMPNirFwxJvN5gM7frPobQQoDPQ05jCJbgDfXbGgJTv7UUFUBJaXBYJ8Z-avxe7IJWZwOK9--EO_xu7sRLvnUcbu3GATPltVeD4y7zUAee2Txe_WQ