GET http://localhost:8080/api/users/profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJleHAiOjE3NTM5MDM2MDAsImlhdCI6MTc1MzY0NDQwMCwibmFtZSI6IkpvaG4gRG9lIiwicm9sZUlkIjoyLCJyb2xlTmFtZSI6InVzZXIiLCJzdWIiOjEsInVzZXJuYW1lIjoiam9obmRvZSJ9.TJlLg-Qypkq-XTtPkhxM_6BCS7hF4zeYd2YAmgRH-wPbDLWwOzFBqpd7W_0tHRU926ZsUlmkDpV1aTCcODKc0NPn0yt5TRRk4-GMRhnqQO-Qi8v8ORU8fDskMoCeNeKkQmf35wrjZrjg0pe2cR0fUbeNZmWsvp-mUmRM58Mx0nHc-dWGbcHuR4eTBD-xaj9hyUCP4rDbyUMtiuzxOvm96YZg4Liyj0zD-r5KTa4df0U7xfmkOCk3jN1_GEajki8cmCY1fstwXTXPIpjWEskc00xE7eSv0vU4cmmJr58BjgiwKVhgnZjS7qtytqxC2YyhQWDQ0uilAHVvreojQbEk6A
